FROM python:3.11-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir meltano

WORKDIR /project
COPY meltano.yml .

RUN meltano install extractor tap-csv
RUN meltano install loader target-clickhouse

CMD ["meltano", "run", "tap-csv", "target-clickhouse"]
